name: Documentation Build

on: [push, pull_request]

jobs:
  docbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: docs
      - run: pixi run --environment docs docbuild
  doctest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: docs
      - run: pixi run --environment docs doctest
